function initPlay() {
    setCast("Google US English", "Google UK English Male");
    // goTime(24);
    // setCast("Microsoft Zira", "Microsoft David");
}

let _ = goTime; // Next marker

play.script = [
    // {action:panel},
    {voice:0, rate:1, pitch:1},
    "Today's lesson is about algebra.",
    {pause:2000},
    "In physics, relationships between variables are often described by equations.",
    "You've probably seen some of these equations in your previous science courses.",
    {pause:2000}, {action:_},
    "Suppose we have an equation; y = 3x + 8.",
    "This tells us how to calculate y, when we know x.",
    "But what if we already know the value of y, and want to find x instead?",
    {pause:1000},
    "We need to rearrange the equation, to isolate x.",
    {pause:2000}, {action:_},
    "The basic idea is that we can perform any operation on an equation, as long as we do the same thing to both sides.",
    "To isolate x, we need to undo the multiplication by 3, and the addition of 8",
    {action:_, pause:2000},
    "We can cancel any operation by performing its inverse.",
    "For example, subtraction cancels with addition, and division cancels with multiplication.",
    "Inverse operations only cancel if they are performed consecutively.",
    "This means that when we undo an operation, we must follow order of operations in reverse.",
    {action:_, pause:1000},
    "For this equation, we would start by subtracting 8 from both sides.",
    {action:_, pause:1000},
    "The addition and subtraction of 8 on the right side can be cancelled.",
    {action:_, pause:1000},
    "Now we can rewrite the equation without the cancelled parts.",
    {action:_, pause:3000},
    "Next, we need to remove the factor 3 from the right side.",
    "To do this, we divide both sides of the equation by 3.",
    {action:_, pause:3000},
    "Now we can cancel the multiplication and division by 3.",
    {action:_, pause:1000},
    "Again, we rewrite the equation without the cancelled parts.",
    {action:_, pause:1000},
    "Now we have isolated our unknown, x, because it is all alone on the right side.",
    "We can now evaluate x, by substituting the given value of y = 20.",
    {action:_, pause:4000},
    "We can check that our answer is correct, by substituting it back in to the original equation.",
    {action:_},
    "Since 3 times 4 plus 8 equals 20 -- which is the correct value for y",
    "our solution, x = 4, is correct.",
    {pause:2000},
    {action:_}, // 13
    "Now let's look at a physics word problem.",
    {pause:1500},
    "A ball falls from rest, to a final velocity of negative 12.0 metres per second, just before it reaches the ground.",
    "Assuming that the acceleration of the ball is negative 9.81 metres per second squared, use algebra to calculate the time it takes the ball to fall.",
    {pause:1000},
    "The equation needed to solve this problem is shown on the screen.",
    {pause:2000}, {action:_},
    "The first thing we want to do, is to identify the values of the variables that are known.",
    {action:_},
    "Negative 12.0 metres per second is the final velocity of the ball, represented by the symbol v subscript f.",
    {action:_},
    "Negative 9.81 metres per second squared is the acceleration, represented by the symbol A.",
    {action:_}, // 17
    "Because the ball begins from rest, its initial velocity, v subscript i, is zero.",
    {pause:1000},
    "The unknown in the equation is delta t, the time it takes the ball to fall.",
    {pause:1000},
    "When the unknown we are isolating appears in the denominator of a fraction, we should start by moving it to the other side of the equation.",
    {action:_},
    "To do this, multiply both sides by delta t.",
    {pause:750}, {action:_},
    "Now cancel the delta t's on the right side.",
    {pause:750}, {action:_}, // 20
    "And rewrite the equation without the cancelled parts.",
    {pause:2000}, {action:_},
    "Next, divide both sides by a.",
    {pause:1000}, {action:_},
    "And then cancel the a's from the left side.",
    {pause:1000}, {action:_},
    "We have now isolated the unknown, delta t.",
    {pause:1000}, {action:_}, // 24
    "Now we can evaluate delta t by substituting the values of the other variables.",
    {action:_, pause:1500},
    {action:_, pause:3000},
    {action:_},
    "We can check that our answer is correct by substituting it back into the original equation.",
    {pause:1000}, {action:_},
    "If we use the unrounded answer for delta t, we should get negative 9.81 metres per second squared for a.",
    {pause:1000},
    "If we use the value of delta t, rounded to only 3 significant digits, there could be a small error in the third digit.",
    {action:_},
];
