let p30 = {title:"Physics 30", id:"p30", cal:{1:"5dd9fa5a", 3:"899b6b84"},
    grc:{1:"u/0/w/NTM1MTM4ODU1NTRa", 3:"u/0/w/MTg4NTA4MTEyM1pa"}, menu:[
    {title:"Unit 1 - Momentum & Impulse", id:"momentum", menu:[
        {title:"Work & Energy Review", id:"work"},
        {title:"Momentum", id:"p"},
        {title:"Impulse", id:"impulse"},
        {title:"Momentum Conservation", id:"pCons"},
        {title:"Elastic & Inelastic Collisions", id:"coll"},
        {title:"2D Vectors Review", id:"rev2d"},
        {title:"2D Collisions", id:"coll2d"},
    ]},
    {title:"Unit 2 - Electric & Magnetic Fields", id:"em", menu:[
        {title:"Electrostatics", id:"estat"},
        {title:"Coulomb’s Law", id:"coul"},
        {title:"Electric Fields", id:"E"},
        {title:"Motion in a Uniform <b>E</b> Field", id:"unifE"},
        {title:"Potential Difference", id:"volt"},
        {title:"Millikan’s Oil Drop Experiment", id:"oil"},
        {title:"Electromagnetism", id:"mag"},
        {title:"Magnetic Fields", id:"hand"},
        {title:"Magnetic Force", id:"qvB"},
        {title:"Motion in a Uniform <b>B</b> Field", id:"helix"},
        {title:"Motor Principle", id:"motor"},
        {title:"Electromagnetic Induction", id:"farad"},
    ]},
    {title:"Unit 3 - Electromagnetic Radiation", id:"emr", menu:[
        {title:"EM Waves (Maxwell’s Theory)", id:"maxwell"},
        {title:"Speed of Light", id:"c"},
        {title:"Young's Experiment", id:"young"},
        {title:"Single-Slit Diffraction", id:"diffract"},
        {title:"Refraction", id:"snell"},
        {title:"Ray Diagrams", id:"ray"},
        {title:"Principal Rays", id:"prRay"},
        {title:"Mirror Equation", id:"mirror"},
        {title:"Lenses", id:"lens"},
        {title:"Thermal (Blackbody) Radiation", id:"bbr"},
        {title:"Photons", id:"photon"},
        {title:"Photoelectric Effect", id:"pe"},
        {title:"X-Rays", id:"xray"},
        {title:"Compton Effect", id:"compton"},
    ]},
    {title:"Unit 4 - Atoms & Nuclei", id:"matter", menu:[
        {title:"Thomson’s CRT Experiment", id:"crt"},
        {title:"Atomic Models", id:"atom"},
        {title:"Wave-Particle Duality", id:"deBrog"},
        {title:"Bohr’s Model of Hydrogen", id:"bohr"},
        {title:"Mass Spectrometry & Isotopes", id:"iso"},
        {title:"Radioactivity", id:"Bq"},
        {title:"Nuclear Reactions", id:"nuke"},
        {title:"Half-life", id:"half"},
        {title:"Nuclear Energy", id:"mc2"},
        {title:"Fission & Fusion", id:""},
        {title:"Standard Model", id:"quark"},
    ]},
    {title:"Documents & Links", id:"link30", menu:[
        {title:"Salisbury Composite", open:"https://salcomp.ca"},
        {title:"Video", youtube:{list:"PLpVmtCaB-lykMzpjcg79la6effekhfsJq"}},
    ]},
]};

let home = {title:"Mr. Mac’s Home", id:"home", menu:[p30]};
