let cs = {title:"Computing Science 10", id:"cs10", grc:"u/0/w/NTQ2MzI2ODA1ODRa", menu:[
    {title:"Structured Programming 1 & 2", id:"sp", menu:[
        {title:"Intro to Programming", id:"intro"},
        {title:"Integrated Development Environments", id:"ide"},
        {title:"Programming in Python", id:"python"},
        {title:"Comments & Docstrings", id:"comment"},
        {title:"Variables", id:"var"},
        {title:"Input & Output", id:"io"},
        {title:"Data Types (Classes)", id:"type"},
        {title:"Modules & Packages", id:"mod"},
        {title:"Operators", id:"oper"},
        {title:"Boolean Values & Operators", id:"bool"},
        {title:"Conditional Statements", id:"if"},
        {title:"Loops", id:"while"},
        {title:"Flags & Counters", id:"flag"},
        {title:"Iteration & Searching", id:"for"},
        {title:"Formatted Output", id:"format"},
        {title:"Accumulation", id:"accum"},
        {title:"String Methods", id:"str"},
    ]},
    {title:"Computer Science 1", id:"cs1", menu:[
        {title:"Binary Encoding", open:"https://drive.google.com/open?id=1uD73FDAhv1AiH5rVPLIsZn-acMjGY09gNxLbEozjDA4"},
        {title:"Text Encoding", open:"https://drive.google.com/open?id=1wGMBQAUTTSNcbZPeNOf8BO6yVw7p2yHcHxeQ-acCbyM"},
        {title:"Von Neumann Architecture", open:"https://drive.google.com/open?id=1dQAlZuVoWrzjZT-19dEB5gvnysCwPRGYu_AkQPQooMg"},
        {title:"Computing Science", open:"https://drive.google.com/open?id=13cPWZNfIyKYM6DPi_IxaVgUSj0b8II1kCzZVfvLZyOc"},
        {title:"Algorithms", open:"https://drive.google.com/open?id=1Gha5Y-KxghYX_1blLUVHf5DWXEipkk0AVWZMW-ZxVzw"},
        // {title:"Summative Assessment", href:""},
    ]},
    {title:"Robotics Programming 1 & 2", id:"robo", menu:[
        {title:"Intro to Robotics", id:"robo_intro"},
        {title:"Turning the Robot", id:"turn"},
        {title:"Functions & Arguments", id:"func"},
        {title:"Colours & Sensors", id:"colour"},
        {title:"Soccer Challenge", id:"soccer"},
        {title:"Lists", id:"list"},
        {title:"Parking Lot Challenge", id:"park"}
    ]},
    {title:"Documents & Links", id:"link_cs10", menu:[
        {title:"Course Outline", open:"https://docs.google.com/document/d/1ElD-IF84gr2epoYlVpRtMFDyBv3EEbhGF0moBBoObSE/edit#heading=h.gjdgxs"},
        {title:"OneDrive Instructions", open:"https://support.microsoft.com/en-ca/office/sync-with-onedrive-bb89981b-e382-4969-b8fd-d413a90b6db3?ui=en-CA&rs=en-CA&ad=CA"},
        {title:"Thonny", open:"https://thonny.org/"},
        {title:"Python Documentation", open:"https://docs.python.org/3/"},
        {title:"sc8pr Documentation", open:"https://dmaccarthy.github.io/sc8pr/"},
        {title:"Pygame Documentation", open:"https://www.pygame.org/docs/"},
        // {title:"Email Mr. MacCarthy", open:"mailto:david.maccarthy@eips.ca"},
        // {title:"Salisbury Composite", open:"https://salcomp.ca"},
        // {title:"More...", id:"../../../home"},
    ]},
]};

let home = {title:"Mr. Mac's Home", id:"home", menu:[cs]};
